### ISSUE TITLE
Installation fails because of authentification

### ISSUE THREAD

**Issue by Rokko11** [netz98/n98-magerun2#155]
Hi!

I try to install Magento 2 via command-line-script. It fails, because the URL `https://repo.magento.com/packages.json` returns the String `Authorization needed`

The Log:

```
Successfully installed composer to Magento root
Found executable /var/www/virtual/.../html/composer.phar



  [Composer\Downloader\TransportException]                                   
  The 'https://repo.magento.com/packages.json' URL required authentication.  
  You must be using the interactive console to authenticate                  


The "/var/www/virtual/.../html/pub/media" directory does not exist.
Start installation process.



  [RuntimeException]                  
  Installation script was not found.  
```

Kind regards,
Rokko

**Comment by Rokko11** [comment]
Sorry, this is definitely not a magerun-issue. When installing Magento via git clone and composer, same error occurs.

```

  - Installing seld/jsonlint (1.3.1)
    Downloading: 100%         

  - Installing composer/composer (1.0.0-alpha10)
    Downloading: 100%         

  - Installing magento/composer (1.0.2)
    Authentication required (repo.magento.com):
      Username: 
```
