### ISSUE TITLE
How do I include my own Magento repo to download Magento Commerce version?

### ISSUE THREAD

**Issue by maurisource** [netz98/n98-magerun2#710]
Hi, can someone enlighten me on how to make Magerun2 use my auth.json file located at ~/composer/auth.json on my mac? This file contains my Magento repo credentials as used by Composer.

I'm trying to get Magerun2 to automate the installation of Magento Commerce version, but it won't show up in the list when firing `magerun2 install`. I'm only able to see CE versions in there.

Please advise

**Comment by cmuench** [comment]
It's only a wrapper around composer.
The distro config is defined here:

https://github.com/netz98/n98-magerun2/blob/develop/config.yaml#L293

You can add your own config yaml and n98-magerun2 will merge your config.
See: https://github.com/netz98/n98-magerun2/wiki/Config

**Comment by maurisource** [comment]
@cmuench 
Thanks for pointing in the right direction. 
I understood that I can add my own Magento Repo credentials to a system wide config file placed here: /etc/n98-magerun2.yaml

But I'm not seeing any command example to follow in order to input something like this
```
        "repo.magento.com": {
            "username": "<public-key>",
            "password": "<private-key>"
        }
```

**Comment by cmuench** [comment]
@maurisource n98-magerun2 asks for the credentials if they are unknown for Composer. You can add the Keys with composer.
`composer.phar global config http-basic.repo.magento.com <public_key> <private_key>`

**Comment by maurisource** [comment]
@cmuench 
Yes, my composer --global config has the public_key and private_key stored already.
I have placed a system wide config file here as instructed: /etc/n98-magerun2.yaml

```
magento-packages:
      - name: magento-ee-2.4.1
        package: magento/project-enterprise-edition
        version: 2.4.1
        options:
          prefer-dist: true
          stability: alpha
          repository-url: https://repo.magento.com
```

But when I run `magerun2 install` I only see the following choices, no sign of magento-ee-2.4.1


```
Choose a magento version:
  [1] magento-ce-2.4.1 
  [2] magento-ce-2.4.0 
  [3] magento-ce-2.3.5-p2 
  [4] magento-ce-2.3.5 
  [5] magento-ce-2.3.4 
  [6] magento-ce-2.3.3 
  [7] magento-ce-2.3.2 
  [8] magento-ce-2.3.1 
  [9] magento-ce-2.3.0 

```

**Comment by ktomk** [comment]
AFAIK the magento versions are also loaded from the config, not from any remote repository/ies. See the earlier link about the config:

> You can add your own config yaml and n98-magerun2 will merge your config.
> See: https://github.com/netz98/n98-magerun2/wiki/Config

@maurisource

**Comment by cmuench** [comment]
There are some config keys missing:

```
commands:
  N98\Magento\Command\Installer\InstallCommand:
    magento-packages:
       - name: magento-ee-2.4.1
          package: magento/project-enterprise-edition
          version: 2.4.1
          options:
            prefer-dist: true
            stability: alpha
            repository-url: https://repo.magento.com
```

**Comment by maurisource** [comment]
@cmuench Added the config keys, I can see this now

```
macpro@iMac m242 % magerun2 install
                       
In ErrorHandler.php line 61:
                                                                                                                                                   
  Notice: Undefined index: installation in phar:///usr/local/bin/magerun2/src/N98/Magento/Command/Installer/SubCommand/PreCheckPhp.php on line 32 
```

**Comment by ktomk** [comment]
It is this line: https://github.com/netz98/n98-magerun2/blob/develop/src/N98/Magento/Command/Installer/SubCommand/PreCheckPhp.php#L32

Perhaps this is caused by removing keys from the configuration that were previously there. Do you get the error as well when you use the default configuration with a default package?

In Trouble-Shooting using the `-vvv` option can also be of help, it shows which configuration files are loaded. @maurisource

**Comment by maurisource** [comment]
@ktomk No I don't get this error with the default configuration with the default packages.
All I'm trying to do is to get Magerun2 install the EE requested package version.
This is only happening when I'm adding this config file `~/.n98-magerun2.yaml` with those lines:

commands:
  N98\Magento\Command\Installer\InstallCommand:
magento-packages:
      - name: magento-ee-2.4.1
        package: magento/project-enterprise-edition
        version: 2.4.1
        options:
          prefer-dist: true
          stability: alpha
          repository-url: https://repo.magento.com

**Comment by ktomk** [comment]
I suspect this is because of the config merge, the new install command *may* remote the other entries?! Can you run a quick test copying over from the default configuration the setting _`['pre-check']['php']['extensions']`_[Ref] there, too? I'm guessing here a bit, but this is what comes to mind.

[Ref]:https://github.com/netz98/n98-magerun2/blob/develop/config.yaml#L359-L376
\[Ref]:  https://github.com/netz98/n98-magerun2/blob/develop/config.yaml#L359-L376

**Comment by maurisource** [comment]
Corrected config file to this:

`commands:
  N98\Magento\Command\Installer\InstallCommand:
      - name: magento-ee-2.4.1
        package: magento/project-enterprise-edition
        version: 2.4.1
        options:
          prefer-dist: true
          stability: alpha
          repository-url: https://repo.magento.com

installation:
      pre-check:
        php:
          extensions:
            - pdo_mysql
            - spl
            - dom
            - simplexml
            - hash
            - curl
            - iconv
            - ctype
            - gd
            - xsl
            - openssl
            - intl
            - mbstring
            - zip`

No errors but however, magerun2 install shows only these choices. I still can't get the required version:

`  Magento 2 Installation  
                          

Choose a magento version:
  [1] magento-ce-2.4.1 
  [2] magento-ce-2.4.0 
  [3] magento-ce-2.3.5-p2 
  [4] magento-ce-2.3.5 
  [5] magento-ce-2.3.4 
  [6] magento-ce-2.3.3 
  [7] magento-ce-2.3.2 
  [8] magento-ce-2.3.1 
  [9] magento-ce-2.3.0 
 > `

**Comment by cmuench** [comment]
The "magento-packages" key is missing.

**Comment by maurisource** [comment]
Thanks for your help, it worked guys!
I posted the solution on my blog as well, in case someone else might be looking to do this using Magerun2 :)
[](https://maurisource.com/magento-enterprise-commerce-magerun2/)

**Comment by ktomk** [comment]
The YAML still looks fishy so it's not clear to me if there is actually an issue when merging the configs for the install sub-command regarding the pre-check flights config-tree or not.

In pipelines I've integrated JSON schema checks which can be applied to YAML files directly, no idea if that looks like an option for you @cmuench.

**Comment by maurisource** [comment]
@ktomk I corrected the YAML as you can see on my blog it looks like this now:
```
commands:
  N98\Magento\Command\Installer\InstallCommand:
    magento-packages:
      - name: magento-ee-2.4.1
        package: magento/project-enterprise-edition
        version: 2.4.1
        options:
          prefer-dist: true
          stability: alpha
          repository-url: https://repo.magento.com

installation:
      pre-check:
        php:
          extensions:
            - pdo_mysql
            - spl
            - dom
            - simplexml
            - hash
            - curl
            - iconv
            - ctype
            - gd
            - xsl
            - openssl
            - intl
            - mbstring
            - zip
```

I think what would be great is a subcommand in Magerun2 to add our own Authorization keys, and then offer a populated choice list to install with either CE or EE versions.
