### ISSUE TITLE
Add Magento 2.4.2

### ISSUE THREAD

**Issue by kirill533** [netz98/n98-magerun2#713]
Please, add support for installation of Magento 2.4.2. Thanks!

**Comment by cmuench** [comment]
@kirill533 I update the development version.
It's really stable and I will try to release soon.

In the meantime you can manually upgrade by `n98-magerun2.phar self-update --unstable`.

**Comment by kirill533** [comment]
Hi @cmuench , thank you for the update. 

In a meantime I have learned to use **.n98-magerun2.yaml** for adding new versions before the new magerun release comes out:
```
commands:
  N98\Magento\Command\Installer\InstallCommand:
    magento-packages:
      - name: magento-ce-2.4.2
        package: magento/project-community-edition
        version: 2.4.2
        options:
          prefer-dist: true
          stability: alpha
          repository-url: https://repo.magento.com
```
